sudo: required
services:
  - docker

before_install:
  - docker build -t sahanratnayake/docker-react -f Dockerfile.dev .

# commands to be executed at running of test
script:
  - docker run sahanratnayake/docker-react npm run test -- --coverage
